### ISSUE TITLE
中文格式化存在字符问题

### ISSUE THREAD

**Issue by fank243** [susisu/atom-markdown-table-editor#15]
![image](https://user-images.githubusercontent.com/5672377/34067073-b29b60c0-e256-11e7-872f-c881e09a351d.png)

如上面这样，使用中文格式存在问题，英文则没有此问题

**Comment by susisu** [comment]
Use a monospaced font that includes glyphs for chinese characters, like [Noto Sans Mono CJK](https://github.com/googlei18n/noto-cjk).
