### ISSUE TITLE
Escape keybinding breaks vim mode

### ISSUE THREAD

**Issue by harmsk** [susisu/atom-markdown-table-editor#16]
For users of the vim-mode[-plus] package (https://github.com/t9md/atom-vim-mode-plus) the escape keybinding is the way to switch between editing modes. It's really useful to switch between modes when editing a markdown table. 

Unfortunately, the escape keybinding of this package means that the table formats rather than switch vim modes.

I've tried to address this by remapping escape. However, this prevents vim mode from working inside of markdown tables:
```cson
"atom-text-editor:not(.mini):not(.autocomplete-active).markdown-table-editor-active": {
  'escape': 'unset!',
  "ctrl-escape"   : "markdown-table-editor:escape",
}
```

**Comment by susisu** [comment]
Thanks for reporting!

I published v1.0.2 which disables Esc keymap in vim-mode.
You can add an alternative key map like this:
``` cson
"atom-text-editor:not(.mini):not(.autocomplete-active).markdown-table-editor-active":
  "ctrl-escape": "markdown-table-editor:escape"
```
