### ISSUE TITLE
Please optimize support for Chinese.

### ISSUE THREAD

**Issue by MrLixintong** [susisu/atom-markdown-table-editor#17]
I typed in a table like this：

![image](https://user-images.githubusercontent.com/20266504/35557943-9f252108-05e1-11e8-9d74-4e76f743f430.png)

`|` characters are not aligned.

---
This information may help you:
1. The width of a Chinese font is equal to `　`, the Unicode value of this character is ``\u3000``.
2. Matches the Chinese regular expression ：`[\u4e00-\u9fa5]`

🙂

**Comment by susisu** [comment]
East Asian characters including Chinese characters are already supported (because I'm Japanese!)
Use a monospaced font that includes glyphs for chinese characters, such as [Noto Sans Mono CJK](https://github.com/googlei18n/noto-cjk).

**Comment by Aaron-Bird** [comment]
Other characters can be used instead of spaces  
Add the character "&#8202;" to the smaller grid and measure whether the width is equal
like this
https://stackoverflow.com/a/8515417
