### ISSUE TITLE
Format on save does not work

### ISSUE THREAD

**Issue by Chucky2401** [susisu/atom-markdown-table-editor#30]
Hello,
I tried to enable/disable this setting, but even it is enabled or not, when I save the document, the format goes away...

![image](https://user-images.githubusercontent.com/53853245/97980055-7c417600-1dd0-11eb-9951-c7296f7453c0.png)

Could you help me?

**Comment by susisu** [comment]
@Chucky2401 Make sure that `Format Type` settings is set to `Normal`.

<img width="682" alt="Screen Shot 2020-11-17 at 10 27 48" src="https://user-images.githubusercontent.com/2443491/99328515-96df1900-28bf-11eb-9552-383779efb502.png">

(The setting name is bad... sorry)

**Comment by Chucky2401** [comment]
It works like a charm! Thank you so much!
